---
- name: default images
  action: |
    glance_image
      name={{ item.name }}
      copy_from={{ item.url }}
      container_format=bare
      disk_format=qcow2
      auth_url=https://{{ endpoints.main }}:35358/v2.0/
      login_tenant_name=admin
      login_password={{ secrets.admin_password }}
      timeout=12000
      {% if client_self_signed_cert is defined -%}
      cacert=/opt/stack/ssl/openstack.crt
      {% endif -%}
  with_items: glance.images
